import { Inter } from 'next/font/google'
import type { Metadata } from 'next';
import '../globals.css'
import VerticalNavbar from "@/components/Admin/Common/VerticalNavbar"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AdminRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className='flex flex-col lg:flex-row'>
      <div className="pr-20">
        {/* @ts-ignore */}
        <VerticalNavbar />
      </div>
      <div>
        { children }
      </div>
    </main>
  )
}